### ISSUE TITLE
workqueue fails to compile for mip32 (undefined reference to `__sync_fetch_and_add_8')

### ISSUE THREAD

**Issue by djkurtz** [axboe/fio#95]
mipsel-cros-linux-gnu-gcc -Wl,-O1 -Wl,-O2 -Wl,--as-needed -Wl,-O1 -Wl,-O2 -Wl,--as-needed -rdynamic -std=gnu99 -Wwrite-strings -Wall -Wdeclaration-after-statement   -D_GNU_SOURCE -include config-host.h  -O2 -pipe -march=mips32 -g -fno-exceptions -fno-unwind-tables   -fno-asynchronous-unwind-tables   -DBITS_PER_LONG=32 -DFIO_VERSION='"fio-2.2.9"' -o fio gettime.o ioengines.o init.o stat.o log.o time.o filesetup.o eta.o verify.o memory.o io_u.o parse.o mutex.o options.o lib/rbtree.o smalloc.o filehash.o profile.o debug.o lib/rand.o lib/num2str.o lib/ieee754.o crc/crc16.o crc/sha512.o crc/crc7.o crc/sha1.o crc/crc32c.o crc/test.o crc/crc32.o crc/murmur3.o crc/crc32c-intel.o crc/xxhash.o crc/sha256.o crc/fnv.o crc/md5.o crc/crc64.o engines/cpu.o engines/mmap.o engines/sync.o engines/null.o engines/net.o memalign.o server.o client.o iolog.o backend.o libfio.o flow.o cconv.o lib/prio_tree.o json.o lib/zipf.o lib/axmap.o lib/lfsr.o gettime-thread.o helpers.o lib/flist_sort.o lib/hweight.o lib/getrusage.o idletime.o td_error.o profiles/tiobench.o profiles/act.o io_u_queue.o filelock.o lib/tp.o lib/bloom.o lib/gauss.o lib/mountcheck.o workqueue.o engines/libaio.o engines/posixaio.o engines/falloc.o engines/e4defrag.o engines/splice.o engines/mtd.o lib/libmtd.o lib/libmtd_legacy.o diskutil.o fifo.o blktrace.o cgroup.o trim.o engines/sg.o engines/binject.o lib/linux-dev-lookup.o fio.o -lrt -laio -lz  -lm  -lpthread -ldl 

workqueue.o: In function `sum_val':
/build/mipsel-o32-generic/tmp/portage/sys-block/fio-9999/work/fio-9999/workqueue.c:202: undefined reference to `__sync_fetch_and_add_8'
/build/mipsel-o32-generic/tmp/portage/sys-block/fio-9999/work/fio-9999/workqueue.c:202: undefined reference to `__sync_fetch_and_add_8'
/build/mipsel-o32-generic/tmp/portage/sys-block/fio-9999/work/fio-9999/workqueue.c:202: undefined reference to `__sync_fetch_and_add_8'
/build/mipsel-o32-generic/tmp/portage/sys-block/fio-9999/work/fio-9999/workqueue.c:202: undefined reference to `__sync_fetch_and_add_8'
/build/mipsel-o32-generic/tmp/portage/sys-block/fio-9999/work/fio-9999/workqueue.c:203: undefined reference to `__sync_fetch_and_add_8'

git bisect result:
# first bad commit: [a9da8ab2169810667aeb26f857a8ac3c056e4d61] First cut at supporting IO offload

**Comment by axboe** [comment]
Try current -git, I fixed it up for platforms without __sync_fetch_and_add()

**Comment by alexander-f** [comment]
This fix does not seem to work on all platforms, in my case armv5tel 32bit.
The problem seems to be that in configure you test for

static int sfaa(int *ptr)
{
  return __sync_fetch_and_add(ptr, 0);
}

(this test is passed: __sync_fetch_and_add          yes, I may also manually compile and link the program), whereas in workqueue.c the signature is

static void sum_val(uint64_t *dst, uint64_t *src)
{
[...]
}

int * is 32 bit, whereas uint64_t * is 64 bit which leads to a link error for __sync_fetch_and_add_8

**Comment by axboe** [comment]
Good point, I've updated configure to use 64-bit types.

**Comment by alexander-f** [comment]
Thank you, fio now compiles and links fine on armv5tel.
