### ISSUE TITLE
fio 3.20 failed to build on linux kernel 5.7

### ISSUE THREAD

**Issue by narasimhabharadwaj** [axboe/fio#1023]
**make**
FIO_VERSION = fio-3.20-57-g6532
    CC crc/crc16.o
    CC crc/crc32.o
    CC crc/crc32c-arm64.o
In file included from crc/crc32c.h:23:0,
                 from crc/crc32c-arm64.c:1:
crc/../arch/arch.h:4:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
make: *** [crc/crc32c-arm64.o] Error 1

**Comment by axboe** [comment]
That's not a kernel issue, I'm guessing your compiler is too old. What does:

$ gcc --version

report?

**Comment by narasimhabharadwaj** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by axboe** [comment]
You need 4.9 or higher, just pushed a change to make that apparent. Sorry...

**Comment by narasimhabharadwaj** [comment]
Thanks
